name = "tempmail-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "tempmail-db"
database_id = "cdf71667-7ddd-4311-8f0a-6360c8221b75"

[triggers]
crons = ["0 * * * *"]

[email]


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
